<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="100" started-at="2019-10-29T11:49:21 EST" finished-at="2019-10-29T11:49:21 EST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="100" started-at="2019-10-29T11:49:21 EST" finished-at="2019-10-29T11:49:21 EST">
      <class name="com.hbt.semillero.servicios.AppTest">
        <test-method status="PASS" signature="invertirCadenaPU(java.lang.String, java.lang.String)[pri:0, instance:com.hbt.semillero.servicios.AppTest@3108bc]" name="invertirCadenaPU" duration-ms="16" started-at="2019-10-29T11:49:21 EST" data-provider="invertirCadenaDataProvider" finished-at="2019-10-29T11:49:21 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[santiago]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ogaitnas]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invertirCadenaPU -->
        <test-method status="FAIL" signature="invertirCadenaPU(java.lang.String, java.lang.String)[pri:0, instance:com.hbt.semillero.servicios.AppTest@3108bc]" name="invertirCadenaPU" duration-ms="5" started-at="2019-10-29T11:49:21 EST" data-provider="invertirCadenaDataProvider" finished-at="2019-10-29T11:49:21 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[pedro]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hector]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [hector] but found [ordep]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [hector] but found [ordep]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.hbt.semillero.servicios.AppTest.invertirCadenaPU(AppTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invertirCadenaPU -->
        <test-method status="PASS" signature="invertirCadenaPU(java.lang.String, java.lang.String)[pri:0, instance:com.hbt.semillero.servicios.AppTest@3108bc]" name="invertirCadenaPU" duration-ms="5" started-at="2019-10-29T11:49:21 EST" data-provider="invertirCadenaDataProvider" finished-at="2019-10-29T11:49:21 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[54321]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invertirCadenaPU -->
      </class> <!-- com.hbt.semillero.servicios.AppTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
